engine: chalkbox.engines.CSSE2002Engine
---
courseCode: CSSE2002
assignment: ass1
submission: /autograder/submission
outputFile: /autograder/results/results.json
dependencies: # optional
  - lib/hamcrest-core-1.3.jar
  - lib/junit-4.12.jar
linterConfig: config/checkstyle.xml # optional
resources: # optional
  - networks/
testDirectory: solutions/correct/test/ # optional
correctSolution: solutions/correct/ # optional
faultySolutions: solutions/faulty/ # optional
assessableTestClasses: # optional
  - tms.intersection.IntersectionTest
  - tms.sensors.DemoPressurePadTest
